<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MailVolt.Transport.Smtp</PackageId>

    <Description>SMTP transport for MailVolt using MailKit</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MailVolt.Core\MailVolt.Core.csproj" />
  </ItemGroup>
</Project>
