<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MailVolt.Transport.Resend</PackageId>

    <Description>Resend transport for MailVolt</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Resend" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MailVolt.Transport.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MailVolt.Core\MailVolt.Core.csproj" />
  </ItemGroup>
</Project>
